const constants = {
    SUCCESS:'Success',
    ERROR:'Error',
    DEFAULT_ERROR:'Something went wrong, try again later',
    VALIDATION_ERROR:'Validation error',
    USER_UPDATE_MESSAGE:'User has been updated successfully.',
    USER_DELETE_MESSAGE:'User has been deleted successfully.',
    DB_ERROR:'Failed to connect to MongoDB:',
    UNAUTHORIZED:'Unauthorized',
    INVALID_CREDENTIALS:'Invalid credentials.',
    EMAIL_EXIST:'Email is already in use.',
    USER_NOT_FOUND:'User not found.',
    EMAIL_REQUIRED:'Email is required',
    INVALID_EMAIL:'Invalid Email',
    PASSWORD_REQUIRED:'Password is required',
    PASSWORD_LENGHT_VALIDATION:'Password must be at least 6 characters long',
    FNAME_REQUIRED:'First name is required',
    LNAME_REQUIRED:'Last name is required',
    GENDER_REQUIRED:'Gender is required',
    GENDER_VALIDATION:'Gender field only accept male or female value',
    USER_TYPE_REQUIRED:'User type is required',
    USER_TYPE_VALIDATION:'User type field only accept customer or seller value',
}

export default constants;